// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a aspect ratio.
 */
export type AspectRatio = number | "auto" | (string & {});
