// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircleShape } from "./CircleShape";
import type { EllipseShape } from "./EllipseShape";
import type { InsetShape } from "./InsetShape";
import type { PathShape } from "./PathShape";
import type { PolygonShape } from "./PolygonShape";

/**
 * Represents a basic shape function for clip-path.
 */
export type BasicShape =
  | { inset: InsetShape }
  | { circle: CircleShape }
  | { ellipse: EllipseShape }
  | { polygon: PolygonShape }
  | { path: PathShape };
