// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicShape } from "./BasicShape";

/**
 * Represents the clip-path property value.
 */
export type ClipPath = BasicShape | string;
