// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proxy type for CSS `Option` serialization/deserialization.
 */
export type CssOption<T> = T | null;
