// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CssGlobalKeyword } from "./CssGlobalKeyword";

/**
 * Represents a CSS property value that can be explicitly set, inherited from parent, or reset to initial value.
 */
export type CssValue<T> = CssGlobalKeyword | T;
