// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Angle } from "./Angle";

/**
 * Represents a single CSS filter operation
 */
export type Filter =
  | { brightness: number }
  | { contrast: number }
  | { grayscale: number }
  | { saturate: number }
  | { "hue-rotate": Angle }
  | { invert: number }
  | { opacity: number };
