// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";

/**
 * A list of filter operations
 */
export type Filters = Array<Filter> | string;
