// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a flex shorthand property for flex-grow, flex-shrink, and flex-basis.
 */
export type Flex =
  | { grow: number | null; shrink: number | null; basis: LengthUnit | null }
  | number
  | "auto"
  | "none"
  | string;
