// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a fraction of the available space
 */
export type FrLengthUnit = { fr: number };
