// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridRepetitionKeyword } from "./GridRepetitionKeyword";

/**
 * Represents a grid track repetition pattern
 */
export type GridRepetitionCount = GridRepetitionKeyword | number;
