// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridPlacementKeyword } from "./GridPlacementKeyword";
import type { GridPlacementSpan } from "./GridPlacementSpan";

/**
 * Represents a grid placement with serde support
 */
export type GridPlacement =
  | GridPlacementKeyword
  | GridPlacementSpan
  | number
  | string;
