// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a grid placement span
 */
export type GridPlacementSpan = { span: number };
