// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrLengthUnit } from "./FrLengthUnit";
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a grid track sizing function with serde support
 */
export type GridLengthUnit = FrLengthUnit | LengthUnit | string;
