// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Procedural noise gradient that generates organic, natural-looking patterns using fractal Brownian motion.
 * This creates dynamic textures that can be used as backgrounds or overlays with customizable parameters
 * for controlling the noise characteristics and visual appearance.
 */
export type NoiseV1 = {
  /**
   * Random seed value that determines the unique noise pattern generated
   */
  seed?: number;
  /**
   * Controls the opacity of the noise pattern. 0.0 is fully transparent, 1.0 is fully opaque
   */
  opacity?: number;
};
