// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a percentage value (0.0-1.0) in CSS parsing.
 *
 * This struct wraps an f32 value that represents a percentage
 * where 0.0 corresponds to 0% and 1.0 corresponds to 100%.
 */
export type PercentageNumber = string | number;
