// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a 2D scale for CSS scale property
 */
export type Scale = { x: number; y: number } | string;
