// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a collection of text decoration lines.
 */
export type TextDecorationLines = Array<"underline" | "line-through">;
