// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { TextDecorationLines } from "./TextDecorationLines";
import type { TextDecorationStyle } from "./TextDecorationStyle";

/**
 * Parsed `text-decoration` value.
 */
export type TextDecoration =
  | {
      line: TextDecorationLines;
      style: TextDecorationStyle | null;
      color: Color | null;
    }
  | string;
