// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents text decoration style options (currently only solid is supported).
 */
export type TextDecorationStyle = "solid";
