// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls whether text should be wrapped.
 */
export type TextWrapMode = "wrap" | "nowrap";
