// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a 2D translation for CSS translate property
 */
export type Translate = { x: LengthUnit; y: LengthUnit } | string;
