// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls how whitespace should be collapsed.
 */
export type WhiteSpaceCollapse =
  | "preserve"
  | "collapse"
  | "preserve-spaces"
  | "preserve-breaks";
