// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextWrapMode } from "./TextWrapMode";
import type { WhiteSpaceCollapse } from "./WhiteSpaceCollapse";
import type { WhiteSpaceKeywords } from "./WhiteSpaceKeywords";

/**
 * Controls how whitespace should be handled.
 */
export type WhiteSpace =
  | WhiteSpaceKeywords
  | { textWrapMode: TextWrapMode; whiteSpaceCollapse: WhiteSpaceCollapse }
  | string;
